### ISSUE TITLE
Support custom matrix formats for `X`

### ISSUE THREAD

**Issue by jkanche** [scverse/anndata#1019]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of anndata.
- [ ] (optional) I have confirmed this bug exists on the master branch of anndata.

### Report

may be instead of the strict checking for `X`, it should allow for users defined custom matrix classes (may be using protocols?). e.g. I've tried to use [backedarray](https://github.com/lilab-bcb/backedarray), or [filebackedarray](https://github.com/BiocPy/FileBackedArray), (the later my own package) but ran into many issues

Code:

```python
>>> import filebackedarray as fba
>>> mat = fba.H5BackedSparseData("tests/data/tenx.sub.h5", "matrix")
>>> import anndata
>>> import pandas as pd
>>> anndata.AnnData(X=mat, obs=pd.DataFrame(index=range(1000)), var=pd.DataFrame(index=range(3005)))
```

Traceback:

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/biocpy/lib/python3.8/site-packages/anndata/_core/anndata.py", line 308, in __init__
    self._init_as_actual(
  File "/opt/miniconda3/envs/biocpy/lib/python3.8/site-packages/anndata/_core/anndata.py", line 465, in _init_as_actual
    raise ValueError(
ValueError: `X` needs to be of one of ndarray, MaskedArray, spmatrix, ZarrArray, ZappyArray, DaskArray, not <class 'filebackedarray.H5Sparse.H5BackedSparseData'>.
```

I could eventually get this to work with `layers` but slicing seems to be problematic. It would be great to establish some standards on whats expected from a matrix to be compatible with `AnnData`

```python
>>> ad = anndata.AnnData(layers={"counts":mat}, obs=pd.DataFrame(index=range(1000)), var=pd.DataFrame(index=range(3005)))
/opt/miniconda3/envs/biocpy/lib/python3.8/site-packages/anndata/_core/anndata.py:120: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
>>>
```

### Versions

```python
>>> import anndata
>>> anndata.__version__


tried both anndata 0.7.8 and 0.9.1
```

**Comment by flying-sheep** [comment]
I’d say this is an enhancement, not a bug. But good point: If there‘s an abstract class that represents what we need from “X”, that should be the type we accept.

**Comment by jkanche** [comment]
I am not sure if i would go with an abstract class in this context. I think [protocols](https://peps.python.org/pep-0544/) are apt

e.g. If all `X` expects is a matrix-like object that can slice and contain a shape property, this would suffice

```python
>>> from typing import Protocol, runtime_checkable
>>> @runtime_checkable
... class MatrixProtocol(Protocol):
...     def __getitem__(self):
...         ...
...         
...     @property
...     def shape(self):
...         ...
... 
>>> class MyMatrix:
...     def __getitem__(self):
...         pass
...     
...     @property
...     def shape(self):
...         pass
...     
...     def do_something_else(self):
...         pass
... 
>>> isinstance(MyMatrix, MatrixProtocol)
True
```

**Comment by ivirshup** [comment]
A broad issue in the python ecosystem is that while things look "array-like", they actually have a number of idiosyncrasies. This is especially the case for indexing. This has started to be addressed by projects like the [array-api](https://data-apis.org/array-api/2022.12/).

There are a number of issues open for other classes, is there a specific class you'd like to see implemented here?

**Comment by flying-sheep** [comment]
Yeah, that’s exactly what I’m worrying here. If we have something that’s exactly specified, we can test it. If we have an enumeration of slightly differently behaving things, we can also test each of them. But if we have an incorrect specification, things will break fast.

**Comment by ivirshup** [comment]
I am interested in getting `xarray.DataArray` supported, since I think they've done a fair bit of work to support a range of different backends, and I believe have done a bunch of compatibility work already.

**Comment by flying-sheep** [comment]
#326 could be reconsidered if we do much more here
