### ISSUE TITLE
`layers` cannot load sparse matrix

### ISSUE THREAD

**Issue by danielsf** [scverse/anndata#1288]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of anndata.
- [ ] (optional) I have confirmed this bug exists on the master branch of anndata.

### Report

If I create an anndata object with a CSR matrix in the `layers` object and write it to h5ad, anndata cannot read it back in.

Code:
```
import numpy as np
import scipy.sparse
import anndata

n_rows = 1000
n_cols = 231
rng = np.random.default_rng(22131)

data = np.zeros(n_rows*n_cols, dtype=int)
chosen = rng.choice(np.arange(n_rows*n_cols), 7700, replace=False)
data[chosen] = rng.integers(1, 400, len(chosen))
data = data.reshape((n_rows, n_cols))

other_data = np.zeros(n_rows*n_cols, dtype=int)
chosen = rng.choice(np.arange(n_rows*n_cols), 5566, replace=False)
other_data[chosen] = rng.integers(1, 400, len(chosen))
other_data = data.reshape((n_rows, n_cols))


var = pd.DataFrame(
    [{'g': f'g_{ii}'} for ii in range(n_cols)]).set_index('g')

obs = pd.DataFrame(
    [{'c': f'c_{ii}'} for ii in range(n_rows)]).set_index('c')

a_data = anndata.AnnData(
    X=scipy.sparse.csr_matrix(data),
    obs=obs,
    var=var,
    layers={'dummy': scipy.sparse.csr_matrix(other_data)})

path = 'junk.h5ad'
a_data.write_h5ad(path)

roundtrip = anndata.read_h5ad(path, backed='r')

x = roundtrip.X[()].toarray()
np.testing.assert_allclose(
    x, data, atol=0.0, rtol=1.0e-6)

other = roundtrip.layers['dummy'][()]
```

Traceback:

```
(dummy_anndata) osxltFMD6W:sparse scott.daniel$ python test.py 
Traceback (most recent call last):
  File "/Users/scott.daniel/KnowledgeBase/garage/sparse/test.py", line 43, in <module>
    other = roundtrip.layers['dummy'][()]
  File "/Users/scott.daniel/miniconda3/envs/dummy_anndata/lib/python3.10/site-packages/scipy/sparse/_index.py", line 44, in __getitem__
    row, col = self._validate_indices(key)
  File "/Users/scott.daniel/miniconda3/envs/dummy_anndata/lib/python3.10/site-packages/scipy/sparse/_index.py", line 147, in _validate_indices
    row, col = _unpack_index(key)
  File "/Users/scott.daniel/miniconda3/envs/dummy_anndata/lib/python3.10/site-packages/scipy/sparse/_index.py", line 284, in _unpack_index
    raise IndexError('invalid number of indices')
IndexError: invalid number of indices
```
Note that the code successfully reads `roundtrip.X[()].toarray()`, but fails on `roundtrip.layers['dummy'][()]`. The bug even occurs if the same data is written both to `X` and `layers/dummy`.

For what it's worth, here is my environment
```
# packages in environment at /Users/scott.daniel/miniconda3/envs/dummy_anndata:
#
# Name                    Version                   Build  Channel
anndata                   0.10.4                   pypi_0    pypi
array-api-compat          1.4                      pypi_0    pypi
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2023.12.12           hecd8cb5_0  
exceptiongroup            1.2.0                    pypi_0    pypi
h5py                      3.10.0                   pypi_0    pypi
libffi                    3.4.4                hecd8cb5_0  
natsort                   8.4.0                    pypi_0    pypi
ncurses                   6.4                  hcec6c5f_0  
numpy                     1.26.3                   pypi_0    pypi
openssl                   3.0.12               hca72f7f_0  
packaging                 23.2                     pypi_0    pypi
pandas                    2.1.4                    pypi_0    pypi
pip                       23.3.1                   pypi_0    pypi
python                    3.10.13              h5ee71fb_0  
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
readline                  8.2                  hca72f7f_0  
scipy                     1.11.4                   pypi_0    pypi
setuptools                68.2.2                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h6c40b1e_0  
style                     1.1.0                    pypi_0    pypi
tk                        8.6.12               h5d9f67b_0  
tzdata                    2023.4                   pypi_0    pypi
update                    0.0.1                    pypi_0    pypi
wheel                     0.41.2                   pypi_0    pypi
xz                        5.4.5                h6c40b1e_0  
zlib                      1.2.13               h4dc903c_0  
```

### Versions

```python
>>> import anndata, session_info
>>> session_info.show(html=False, dependencies=True)
-----
anndata             0.10.4
session_info        1.0.0
-----
cython_runtime      NA
dateutil            2.8.2
exceptiongroup      1.2.0
h5py                3.10.0
natsort             8.4.0
numpy               1.26.3
packaging           23.2
pandas              2.1.4
pytz                2023.3.post1
scipy               1.11.4
six                 1.16.0
zoneinfo            NA
-----
Python 3.10.13 (main, Sep 11 2023, 08:39:02) [Clang 14.0.6 ]
macOS-10.16-x86_64-i386-64bit
-----
Session information updated at 2024-01-05 15:52
```

**Comment by ivirshup** [comment]
Thanks for the bug report!

I don't think this is a bug in anndata, but rather the behaviour (maybe a bug) with scipy sparse matrices.

At the moment, backed mode ONLY supports having the matrix in `X` be backed. So, `layers["dummy"]` is actually already in memory when you try to index into it.

To demonstrate with your example, these two expressions throws the same error: `a_data.X[()]`, `a_data.layers["dummy"][()]`. `sparse.random(10, 10, format="csr")[()]` will throw this error as well.

I don't know off the top of my head whether this is intentional or not with scipy, but you can get the desired effect via indexing with: `[...]` or `[:]`.

I'm going to mark this as closed for now, but let me know if this doesn't quite solve the issue you're running into and we can re-open.
