### ISSUE TITLE
Error with AnnData.__init__(adata,asview = True)

### ISSUE THREAD

**Issue by colganwi** [scverse/anndata#1382]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of anndata.
- [ ] (optional) I have confirmed this bug exists on the master branch of anndata.

### Report

Code:

```python
import anndata as ad
import numpy as np

adata = ad.AnnData(X = np.zeros((8,8)))
adata_view = ad.AnnData(adata,asview = True)
```

Traceback:

```pytb
Traceback (most recent call last):
  File "/lab/solexa_weissman/wcolgan/treedata/test.py", line 5, in <module>
    adata_view = ad.AnnData(adata,asview = True)
  File "/home/wcolgan/miniconda3/envs/td-env/lib/python3.10/site-packages/anndata/_core/anndata.py", line 360, in __init__
    self._init_as_view(X, oidx, vidx)
  File "/home/wcolgan/miniconda3/envs/td-env/lib/python3.10/site-packages/anndata/_core/anndata.py", line 407, in _init_as_view
    obs_sub = adata_ref.obs.iloc[oidx]
  File "/home/wcolgan/miniconda3/envs/td-env/lib/python3.10/site-packages/pandas/core/indexing.py", line 1192, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/wcolgan/miniconda3/envs/td-env/lib/python3.10/site-packages/pandas/core/indexing.py", line 1750, in _getitem_axis
    raise TypeError("Cannot index by location index with a non-integer key")
TypeError: Cannot index by location index with a non-integer key

```

### Versions

```python
-----
anndata             0.10.5.post1
session_info        1.0.0
-----
cython_runtime      NA
dateutil            2.8.2
exceptiongroup      1.2.0
h5py                3.10.0
natsort             8.4.0
numpy               1.26.4
packaging           23.2
pandas              2.2.0
pyarrow             15.0.0
pytz                2024.1
scipy               1.12.0
six                 1.16.0
sphinxcontrib       NA
zoneinfo            NA
-----
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
Linux-5.4.0-137-generic-x86_64-with-glibc2.31
-----
Session information updated at 2024-02-20 12:48
```

**Comment by ivirshup** [comment]
Thanks for opening an issue.

We don't document that argument and wouldn't consider it public API, so I'm inclined to say this isn't a bug.

What are you trying to do here?

**Comment by colganwi** [comment]
I encountered this in a unit test for a new package I'm working on. Clearly this is not a typical use of the __init__.  Closing with no action seem reasonable to me.
