### ISSUE TITLE
i cannot read the h5ad object in a conda environment

### ISSUE THREAD

**Issue by Flu09** [scverse/anndata#1576]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of anndata.
- [ ] (optional) I have confirmed this bug exists on the master branch of anndata.

### Report

Hello I need to be able to read the file for a scvi annotation pipeline. Here is the error. I would appreciate it if you help. Thank you.

```py
non_neurons = sc.read('/path/scvi_annotation_latest/brain.h5ad')
```

```pytb
Traceback (most recent call last):
  File "/path/conda-environments/py-env/lib/python3.8/site-packages/anndata/_io/utils.py", line 156, in func_wrapper
    return func(elem, *args, **kwargs)
  File "/path/conda-environments/py-env/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 510, in read_group
    EncodingVersions[encoding_type].check(
  File "/path/conda-environments/py-env/lib/python3.8/enum.py", line 355, in __getitem__
    return cls._member_map_[name]
KeyError: 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/conda-environments/py-env/lib/python3.8/site-packages/scanpy/readwrite.py", line 112, in read
    return _read(
  File "/path/conda-environments/py-env/lib/python3.8/site-packages/scanpy/readwrite.py", line 700, in _read
    return read_h5ad(filename, backed=backed)
  File "/path/conda-environments/py-env/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 413, in read_h5ad
    d[k] = read_attribute(f[k])
  File "/path/conda-environments/py-env/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/path/conda-environments/py-env/lib/python3.8/site-packages/anndata/_io/utils.py", line 162, in func_wrapper
    raise AnnDataReadError(
anndata._io.utils.AnnDataReadError: Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'> from /.
>>> 
>>> import anndata as ad
>>> 
>>> non_neurons = ad.read_h5ad('/path/scvi_annotation_latest/brain.h5ad')
Traceback (most recent call last):
  File "/path/conda-environments/py-env/lib/python3.8/site-packages/anndata/_io/utils.py", line 156, in func_wrapper
    return func(elem, *args, **kwargs)
  File "/ipath/conda-environments/py-env/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 510, in read_group
    EncodingVersions[encoding_type].check(
  File "/path/conda-environments/py-env/lib/python3.8/enum.py", line 355, in __getitem__
    return cls._member_map_[name]
KeyError: 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/conda-environments/py-env/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 413, in read_h5ad
    d[k] = read_attribute(f[k])
  File "/path/conda-environments/py-env/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/path/conda-environments/py-env/lib/python3.8/site-packages/anndata/_io/utils.py", line 162, in func_wrapper
    raise AnnDataReadError(
anndata._io.utils.AnnDataReadError: Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'> from /.
```

```pycon
>>> with h5py.File('/path/brain.h5ad', 'r') as f:
...     print("File attributes:", dict(f.attrs))
...     if 'uns' in f:
...         print("Attributes in /uns group:", dict(f['uns'].attrs))
... 
File attributes: {'encoding-type': 'anndata', 'encoding-version': '0.1.0'}
Attributes in /uns group: {'encoding-type': 'dict', 'encoding-version': '0.1.0'}
```

### Versions

```python
- anndata=0.7.4=py38h32f6830_0 
  - scvi-tools=0.7.0b0=py_0 
  - h5py=2.10.0=nompi_py38h7442b35_105 
  - hdf5=1.10.6=nompi_h3c11f04_101 
  - python=3.8.6=h852b56e_0_cpython
   - scanpy==1.6.0
```

**Comment by flying-sheep** [comment]
anndata 0.7.4 is very old, it doesn’t even have the `encoding-type` attributes that you see here and that anndata writes these says.

So you need a newer version of anndata to read that file.
