### ISSUE TITLE
scanpy.tl.score_genes fails when run on backed adata

### ISSUE THREAD

**Issue by bkmartinjr** [scverse/anndata#234]
If I load an H5AD in backed mode (`backed="r"`), and call `score_genes()`, it will fail.   Works fine on the same dataset loaded in memory cached mode.

Example (run with scanpy 1.4.2, anndata 0.6.22-post1, and h5py 2.9.0):
```python
>>> ab = anndata.read_h5ad('example-dataset/pbmc3k.h5ad', backed=None)
>>> scanpy.tl.score_genes(ab, ['TNFRSF4', 'CPSF3L', 'ATAD3C'])
>>> ab.obs['score'].head()
index
AAACATACAACCAC-1   -0.113624
AAACATTGAGCTAC-1   -0.219552
AAACATTGATCAGC-1   -0.180511
AAACCGTGCTTCCG-1   -0.217497
AAACCGTGTATGCG-1   -0.093459
Name: score, dtype: float32
>>> 
>>> ab = anndata.read_h5ad('example-dataset/pbmc3k.h5ad', backed="r")
>>> scanpy.tl.score_genes(ab, ['TNFRSF4', 'CPSF3L', 'ATAD3C'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/scanpy/tools/_score_genes.py", line 93, in score_genes
    np.nanmean(_adata[:, gene_pool].X, axis=0), index=gene_pool)  # average expression of genes
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/anndata/core/anndata.py", line 1230, in __getitem__
    return self._getitem_view(index)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/anndata/core/anndata.py", line 1234, in _getitem_view
    return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/anndata/core/anndata.py", line 561, in __init__
    self._init_as_view(X, oidx, vidx)
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/anndata/core/anndata.py", line 633, in _init_as_view
    self._raw = adata_ref.raw[oidx]
  File "/mnt/c/Users/bruce/projects/cellxgene/venv/lib/python3.6/site-packages/anndata/core/anndata.py", line 336, in __getitem__
    if self._adata is not None or not self._adata.isbacked: X = self._X[oidx, vidx]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by flying-sheep** [comment]
Looks like an anndata issue, not a scanpy issue.

**Comment by flying-sheep** [comment]
score_genes now explicitly fails in this case, so it’s actually a scanpy feature request and not a bug, see https://github.com/scverse/scanpy/issues/883

```pytb
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[4], [line 1](vscode-notebook-cell:?execution_count=4&line=1)
----> [1](vscode-notebook-cell:?execution_count=4&line=1) sc.tl.score_genes(a2, ['KIR3DL2-1', 'AL590523.1', 'CT476828.1'])

    [... skipping hidden 1 frame]

File ~/Dev/Python/scverse/scanpy/src/scanpy/tools/_score_genes.py:126, in score_genes(adata, gene_list, ctrl_as_ref, ctrl_size, gene_pool, n_bins, score_name, random_state, copy, use_raw, layer)
    124 if is_backed_type(adata.X) and not use_raw:
    125     msg = f"score_genes is not implemented for matrices of type {type(adata.X)}"
--> [126](https://file+.vscode-resource.vscode-cdn.net/home/phil/Dev/Python/scverse/scanpy/data/~/Dev/Python/scverse/scanpy/src/scanpy/tools/_score_genes.py:126)     raise NotImplementedError(msg)
    128 if random_state is not None:
    129     np.random.seed(random_state)

NotImplementedError: score_genes is not implemented for matrices of type <class 'anndata._core.sparse_dataset._CSRDataset'>
```
