### ISSUE TITLE
Broken docs

### ISSUE THREAD

**Issue by ivirshup** [scverse/anndata#324]
It looks like the doc builds are broken. I think it has to do with intersphinx since I'm getting failures for linking to `pandas.DataFrame.iloc`.

```
anndata/anndata/_core/anndata.py:docstring of anndata.AnnData:68:py:attr reference target not found: pandas.DataFrame.iloc
```

 It looks like this is under the pandas `:py:method:` domain now, which inter sphinx doesn't load (why would it not though?) so even

```
:py:method:`~pandas.DataFrame.iloc`
```

doesn't work:

```
anndata/anndata/_core/anndata.py:docstring of anndata.AnnData:68:Unknown interpreted text role "py:method".
```

@flying-sheep I'm out of depth on sphinx here. Any ideas?

(This was the next issue after some version fixes in #325)

**Comment by ivirshup** [comment]
Ah, never mind. Apparently it's defined with `py:method`, but referred to by `py:meth`. Since it would make too much sense to refer to elements the same way they were defined, except for cases when you do.

**Comment by flying-sheep** [comment]
And it doesn’t make sense at all anyway to refer to properties with `:meth:`.

I’m currently fixing it on the sphinx side in sphinx-doc/sphinx#7068, and a workaround landed in sphinx-doc/sphinx@4198219bb1328a85cffd2ee2a9617e7200fefea5

Please depend on sphinx 2.4.1 and revert your `:attr:`→`:meth:` changes.

**Comment by ivirshup** [comment]
> And it doesn’t make sense at all anyway to refer to properties with :meth:

But it's not how I do it, it's how pandas defines it in their `objects.inv`.

**Comment by flying-sheep** [comment]
Yes, it’s a Sphinx bug. Short summary:

1. A change in Sphinx made autosummary generate the following for properties:

   ```restructuredtext
   .. method:: some_prop
      :property:
   ```

2. The Sphinx maintainer agrees with me that it’s a bug and will be fixed in Sphinx 3.
3. For the time being Sphinx 2.4.1 contains a compatibility hack (sphinx-doc/sphinx@4198219) that makes `:attr:` links work with things that are accidentally filed as methods in `objects.inv`
4. Medium-term my PR (sphinx-doc/sphinx#7068) to properly fix it will be merged and properties will be documented as this:

   ```restructuredtext
   .. attribute:: some_prop
      :property:
   ```

**Comment by ivirshup** [comment]
> For the time being Sphinx 2.4.1 contains a compatibility hack (sphinx-doc/sphinx@4198219) that makes :attr: links work with things that are accidentally filed as methods in objects.inv

Are you sure it's in 2.4.1? The builds have been failing with this error issue on that version of sphinx installed: https://readthedocs.com/projects/icb-anndata/builds/290045/

I'm not sure if this is causal, but this error has been happening since sphinx 2.4.1 was released. The builds had been working with the `:attr:` reference before that. If I try to replace `meth` with `attr` now, I get the exact same error I was getting before but now with sphinx `2.4.2`.

I don't really see why we even have to say whether it's a method or attribute, since it's a unique reference name.

**Comment by flying-sheep** [comment]
100% sure it’s actually in 2.4.0. Click on the commit: It’ll show you which tags have it in them:

![grafik](https://user-images.githubusercontent.com/291575/74823502-188d2080-5307-11ea-98c8-6166fe3862bc.png)

you can also see sphinx-doc/sphinx@33fcd39 in https://github.com/sphinx-doc/sphinx/compare/v2.3.1...v2.4.0

**Comment by ivirshup** [comment]
Then it looks like this might be a separate issue:

Here's the log from my machine running sphinx 2.4.2

<details>
<summary> log and traceback </summary>

```sh
isaac@mimir:~/github/anndata/docs ‹docs-fix›
$ git diff | cat
diff --git a/anndata/_core/anndata.py b/anndata/_core/anndata.py
index 97a029d..46143d8 100644
--- a/anndata/_core/anndata.py
+++ b/anndata/_core/anndata.py
@@ -215,8 +215,8 @@ class AnnData(metaclass=utils.DeprecationMixinMeta):
     :attr:`layers`.
 
     Indexing into an AnnData object can be performed by relative position
-    with numeric indices (like pandas’ :meth:`~pandas.DataFrame.iloc`),
-    or by labels (like :meth:`~pandas.DataFrame.loc`).
+    with numeric indices (like pandas’ :attr:`~pandas.DataFrame.iloc`),
+    or by labels (like :attr:`~pandas.DataFrame.loc`).
     To avoid ambiguity with numeric indexing into observations or variables,
     indexes of the AnnData object are converted to strings by the constructor.
 
isaac@mimir:~/github/anndata/docs ‹docs-fix›
$ make html
Running Sphinx v2.4.2
loading intersphinx inventory from http://docs.h5py.org/en/latest/objects.inv...
loading intersphinx inventory from https://linnarssonlab.org/loompy/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from https://pandas.pydata.org/pandas-docs/stable/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/reference/objects.inv...
loading intersphinx inventory from https://scikit-learn.org/stable/objects.inv...
loading intersphinx inventory from https://zarr.readthedocs.io/en/stable/objects.inv...
[autosummary] generating autosummary for: api.rst, benchmarks.rst, fileformat-prose.rst, index.rst, references.rst, release_notes.rst
[autosummary] generating autosummary for: /Users/isaac/github/anndata/docs/anndata.AnnData.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.write.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.write_csvs.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.write_loom.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.write_zarr.rst, /Users/isaac/github/anndata/docs/anndata.ImplicitModificationWarning.rst, /Users/isaac/github/anndata/docs/anndata.read_csv.rst, /Users/isaac/github/anndata/docs/anndata.read_excel.rst, /Users/isaac/github/anndata/docs/anndata.read_h5ad.rst, /Users/isaac/github/anndata/docs/anndata.read_hdf.rst, /Users/isaac/github/anndata/docs/anndata.read_loom.rst, /Users/isaac/github/anndata/docs/anndata.read_mtx.rst, /Users/isaac/github/anndata/docs/anndata.read_text.rst, /Users/isaac/github/anndata/docs/anndata.read_umi_tools.rst, /Users/isaac/github/anndata/docs/anndata.read_zarr.rst
[autosummary] generating autosummary for: /Users/isaac/github/anndata/docs/anndata.AnnData.T.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.X.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.chunk_X.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.chunked_X.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.concatenate.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.copy.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.filename.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.is_view.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.isbacked.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.isview.rst, ..., /Users/isaac/github/anndata/docs/anndata.AnnData.uns_keys.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.var.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.var_keys.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.var_names.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.var_names_make_unique.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.var_vector.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.varm.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.varm_keys.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.varp.rst, /Users/isaac/github/anndata/docs/anndata.AnnData.write_h5ad.rst
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 6 source files that are out of date
updating environment: [new config] 59 added, 0 changed, 0 removed
reading sources... [100%] release_notes                                                                                        
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] release_notes                                                                                         

Warning, treated as error:
/Users/isaac/github/anndata/anndata/_core/anndata.py:docstring of anndata.AnnData:68:py:attr reference target not found: pandas.DataFrame.iloc
make: *** [html] Error 2
```

</details>

And here's the readthedocs log from when `attr` was used, with the build failure saying it's running 2.4.1 (this log is a bit longer)

<details>
<summary> log and traceback </summary>

```
[rtd-command-info] start-time: 2020-02-17T22:45:04.104542Z, end-time: 2020-02-17T22:45:20.532546Z, duration: 16, exit-code: 2
python /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Running Sphinx v2.4.1
loading translations [en]... done
making output directory... done
loading intersphinx inventory from http://docs.h5py.org/en/latest/objects.inv...
loading intersphinx inventory from https://linnarssonlab.org/loompy/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from https://pandas.pydata.org/pandas-docs/stable/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/reference/objects.inv...
loading intersphinx inventory from https://scikit-learn.org/stable/objects.inv...
loading intersphinx inventory from https://zarr.readthedocs.io/en/stable/objects.inv...
[autosummary] generating autosummary for: api.rst, benchmarks.rst, fileformat-prose.rst, index.rst, references.rst, release_notes.rst
[autosummary] generating autosummary for: /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.write.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.write_csvs.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.write_loom.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.write_zarr.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.ImplicitModificationWarning.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.read_csv.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.read_excel.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.read_h5ad.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.read_hdf.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.read_loom.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.read_mtx.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.read_text.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.read_umi_tools.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.read_zarr.rst
[autosummary] generating autosummary for: /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.T.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.X.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.chunk_X.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.chunked_X.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.concatenate.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.copy.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.filename.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.is_view.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.isbacked.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.layers.rst, ..., /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.uns_keys.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.var.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.var_keys.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.var_names.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.var_names_make_unique.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.var_vector.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.varm.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.varm_keys.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.varp.rst, /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/docs/anndata.AnnData.write_h5ad.rst
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 6 source files that are out of date
updating environment: [new config] 58 added, 0 changed, 0 removed
reading sources... [  1%] anndata.AnnData
reading sources... [  3%] anndata.AnnData.T
reading sources... [  5%] anndata.AnnData.X
reading sources... [  6%] anndata.AnnData.chunk_X
reading sources... [  8%] anndata.AnnData.chunked_X
reading sources... [ 10%] anndata.AnnData.concatenate
reading sources... [ 12%] anndata.AnnData.copy
reading sources... [ 13%] anndata.AnnData.filename
reading sources... [ 15%] anndata.AnnData.is_view
reading sources... [ 17%] anndata.AnnData.isbacked
reading sources... [ 18%] anndata.AnnData.layers
reading sources... [ 20%] anndata.AnnData.n_obs
reading sources... [ 22%] anndata.AnnData.n_vars
reading sources... [ 24%] anndata.AnnData.obs
reading sources... [ 25%] anndata.AnnData.obs_keys
reading sources... [ 27%] anndata.AnnData.obs_names
reading sources... [ 29%] anndata.AnnData.obs_names_make_unique
reading sources... [ 31%] anndata.AnnData.obs_vector
reading sources... [ 32%] anndata.AnnData.obsm
reading sources... [ 34%] anndata.AnnData.obsm_keys
reading sources... [ 36%] anndata.AnnData.obsp
reading sources... [ 37%] anndata.AnnData.raw
reading sources... [ 39%] anndata.AnnData.rename_categories
reading sources... [ 41%] anndata.AnnData.shape
reading sources... [ 43%] anndata.AnnData.strings_to_categoricals
reading sources... [ 44%] anndata.AnnData.to_df
reading sources... [ 46%] anndata.AnnData.transpose
reading sources... [ 48%] anndata.AnnData.uns
reading sources... [ 50%] anndata.AnnData.uns_keys
reading sources... [ 51%] anndata.AnnData.var
reading sources... [ 53%] anndata.AnnData.var_keys
reading sources... [ 55%] anndata.AnnData.var_names
reading sources... [ 56%] anndata.AnnData.var_names_make_unique
reading sources... [ 58%] anndata.AnnData.var_vector
reading sources... [ 60%] anndata.AnnData.varm
reading sources... [ 62%] anndata.AnnData.varm_keys
reading sources... [ 63%] anndata.AnnData.varp
reading sources... [ 65%] anndata.AnnData.write
reading sources... [ 67%] anndata.AnnData.write_csvs
reading sources... [ 68%] anndata.AnnData.write_h5ad
reading sources... [ 70%] anndata.AnnData.write_loom
reading sources... [ 72%] anndata.AnnData.write_zarr
reading sources... [ 74%] anndata.ImplicitModificationWarning
reading sources... [ 75%] anndata.read_csv
reading sources... [ 77%] anndata.read_excel
reading sources... [ 79%] anndata.read_h5ad
reading sources... [ 81%] anndata.read_hdf
reading sources... [ 82%] anndata.read_loom
reading sources... [ 84%] anndata.read_mtx
reading sources... [ 86%] anndata.read_text
reading sources... [ 87%] anndata.read_umi_tools
reading sources... [ 89%] anndata.read_zarr
reading sources... [ 91%] api
reading sources... [ 93%] benchmarks
reading sources... [ 94%] fileformat-prose
reading sources... [ 96%] index
reading sources... [ 98%] references
reading sources... [100%] release_notes

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  1%] anndata.AnnData
writing output... [  3%] anndata.AnnData.T
writing output... [  5%] anndata.AnnData.X
writing output... [  6%] anndata.AnnData.chunk_X
writing output... [  8%] anndata.AnnData.chunked_X
writing output... [ 10%] anndata.AnnData.concatenate
writing output... [ 12%] anndata.AnnData.copy
writing output... [ 13%] anndata.AnnData.filename
writing output... [ 15%] anndata.AnnData.is_view
writing output... [ 17%] anndata.AnnData.isbacked
writing output... [ 18%] anndata.AnnData.layers
writing output... [ 20%] anndata.AnnData.n_obs
writing output... [ 22%] anndata.AnnData.n_vars
writing output... [ 24%] anndata.AnnData.obs
writing output... [ 25%] anndata.AnnData.obs_keys
writing output... [ 27%] anndata.AnnData.obs_names
writing output... [ 29%] anndata.AnnData.obs_names_make_unique
writing output... [ 31%] anndata.AnnData.obs_vector
writing output... [ 32%] anndata.AnnData.obsm
writing output... [ 34%] anndata.AnnData.obsm_keys
writing output... [ 36%] anndata.AnnData.obsp
writing output... [ 37%] anndata.AnnData.raw
writing output... [ 39%] anndata.AnnData.rename_categories
writing output... [ 41%] anndata.AnnData.shape
writing output... [ 43%] anndata.AnnData.strings_to_categoricals
writing output... [ 44%] anndata.AnnData.to_df
writing output... [ 46%] anndata.AnnData.transpose
writing output... [ 48%] anndata.AnnData.uns
writing output... [ 50%] anndata.AnnData.uns_keys
writing output... [ 51%] anndata.AnnData.var
writing output... [ 53%] anndata.AnnData.var_keys
writing output... [ 55%] anndata.AnnData.var_names
writing output... [ 56%] anndata.AnnData.var_names_make_unique
writing output... [ 58%] anndata.AnnData.var_vector
writing output... [ 60%] anndata.AnnData.varm
writing output... [ 62%] anndata.AnnData.varm_keys
writing output... [ 63%] anndata.AnnData.varp
writing output... [ 65%] anndata.AnnData.write
writing output... [ 67%] anndata.AnnData.write_csvs
writing output... [ 68%] anndata.AnnData.write_h5ad
writing output... [ 70%] anndata.AnnData.write_loom
writing output... [ 72%] anndata.AnnData.write_zarr
writing output... [ 74%] anndata.ImplicitModificationWarning
writing output... [ 75%] anndata.read_csv
writing output... [ 77%] anndata.read_excel
writing output... [ 79%] anndata.read_h5ad
writing output... [ 81%] anndata.read_hdf
writing output... [ 82%] anndata.read_loom
writing output... [ 84%] anndata.read_mtx
writing output... [ 86%] anndata.read_text
writing output... [ 87%] anndata.read_umi_tools
writing output... [ 89%] anndata.read_zarr
writing output... [ 91%] api
writing output... [ 93%] benchmarks
writing output... [ 94%] fileformat-prose
writing output... [ 96%] index
writing output... [ 98%] references
writing output... [100%] release_notes

/home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/envs/latest/lib/python3.6/site-packages/setuptools_scm/git.py:68: UserWarning: "/home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest" is shallow and may cause errors
  warnings.warn('"{}" is shallow and may cause errors'.format(wd.path))

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/envs/latest/lib/python3.6/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/envs/latest/lib/python3.6/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/envs/latest/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/envs/latest/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/envs/latest/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 535, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/envs/latest/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 545, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/envs/latest/lib/python3.6/site-packages/sphinx/util/logging.py", line 219, in pending_warnings
    memhandler.flushTo(logger)
  File "/home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/envs/latest/lib/python3.6/site-packages/sphinx/util/logging.py", line 184, in flushTo
    logger.handle(record)
  File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/logging/__init__.py", line 861, in handle
    rv = self.filter(record)
  File "/home/docs/.pyenv/versions/3.6.8/lib/python3.6/logging/__init__.py", line 720, in filter
    result = f.filter(record)
  File "/home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/envs/latest/lib/python3.6/site-packages/sphinx/util/logging.py", line 404, in filter
    raise SphinxWarning(location + ":" + message)
sphinx.errors.SphinxWarning: /home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/anndata/_core/anndata.py:docstring of anndata.AnnData:68:py:attr reference target not found: pandas.DataFrame.iloc

Warning, treated as error:
/home/docs/checkouts/readthedocs.org/user_builds/icb-anndata/checkouts/latest/anndata/_core/anndata.py:docstring of anndata.AnnData:68:py:attr reference target not found: pandas.DataFrame.iloc
```

</details>

**Comment by flying-sheep** [comment]
Ahah. Because the workaround only works for local references. It’s broken for intersphinx references, because for intersphinx references, `resolve_xref` always returns `None` and a `missing-reference` event handles the actual work.

**Comment by ivirshup** [comment]
Yup. Should be just remove the link for now?

**Comment by flying-sheep** [comment]
Yes, by making them `:attr:` links and adding them to `nitpick_ignore`. They’ll fail to create links without breaking the build, until sphinx is fixed when they’ll automatically start working again.

**Comment by ivirshup** [comment]
It's happening again. But this time it's a property in the "stable" `objects.inv`, but a method in the "latest" `objects.inv`.

**Comment by flying-sheep** [comment]
So we have ``:meth:`thing.appearing.in.objects.inv` `` and it’s not being found?

**Comment by ivirshup** [comment]
It's not a `meth` in pandas `objects.inv` for the current release, it's a property. In the previous release, and in the development version it's a method. So I've just added it to the nitpick ignore, since this seems like a transient issue on pandas end.
