### ISSUE TITLE
Bug in saving view of anndata in backed mode

### ISSUE THREAD

**Issue by kaizhang** [scverse/anndata#718]
When `isbacked == True and is_view == True` and the destination file is the same file, anndata will skip writing the `X` and cause unexpected behaviors.

## Code to reproduce:

```python
import numpy as np
import anndata as ad

print(ad.__version__)

n_obs, n_vars = 5, 7
X = np.random.randint(1, 10, (n_obs, n_vars))
adata = ad.AnnData(X, dtype=np.int8)
adata.write("test.h5ad")

adata = ad.read_h5ad("test.h5ad", backed="r+")
adata[3:].write()

adata = ad.read_h5ad("test.h5ad", backed="r+")
print(adata.X[...])

adata = ad.read_h5ad("test.h5ad")
```

## Output:

```
0.7.8
[[4 8 3 7 3 5 7]
 [7 7 2 6 2 3 6]
 [1 2 4 6 2 1 5]
 [7 1 5 7 9 7 4]
 [7 5 7 9 1 4 4]]
Traceback (most recent call last):
  File "t.py", line 18, in <module>
    adata = ad.read("test.h5ad")
  File "/home/kaizhang/data/software/miniconda3/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 437, in read_h5ad
    return AnnData(**d)
  File "/home/kaizhang/data/software/miniconda3/lib/python3.8/site-packages/anndata/_core/anndata.py", line 308, in __init__
    self._init_as_actual(
  File "/home/kaizhang/data/software/miniconda3/lib/python3.8/site-packages/anndata/_core/anndata.py", line 526, in _init_as_actual
    self._check_dimensions()
  File "/home/kaizhang/data/software/miniconda3/lib/python3.8/site-packages/anndata/_core/anndata.py", line 1837, in _check_dimensions
    raise ValueError(
ValueError: Observations annot. `obs` must have number of rows of `X` (5), but has 2 rows.
```

**Comment by flying-sheep** [comment]
this is still a valid issue, I updated the code to work today (read → read_h5ad)
