### ISSUE TITLE
Issue with the AnnLoader in multiple processing

### ISSUE THREAD

**Issue by ChrisHTV** [scverse/anndata#767]
Hi, 
I had a problem in my pytorch code when I put the num_workers argument in the instantiation of the AnnLoader to a positive integer. First, pytorch threw a TypeError when I started training, so I thought that pytorch had a problem with the AnnData format, but then I realised that I can reproduce the error with the AnnLoader alone, without using the pytorch Trainer.
Then I thought it had to do with my dataset, but fortunately I could reproduce the error with random data. Errors occur:

1. either when I put the num_workers argument in the instantiation of the AnnLoader to a positive integer
2. or when I put the batch_size argument in the instantiation of the AnnLoader to 1 instead of more.

 So here is the small python code example that throws the error:

```
from anndata import AnnData
from anndata.experimental.pytorch import AnnLoader
import numpy as np

A = np.random.rand(200, 10)
ad = AnnData(A, dtype = np.ndarray)

dataloader1 = AnnLoader(ad, batch_size = 2, num_workers = 0)
dataloader2 = AnnLoader(ad, batch_size = 2, num_workers = 1)
dataloader3 = AnnLoader(ad, batch_size = 1, num_workers = 0)

# works
next(iter(dataloader1))

#error
next(iter(dataloader2))

#error
next(iter(dataloader3))
```

error n°1:
```
Traceback (most recent call last):
  File "/storage/groups/ml01/workspace/christophe.vetter/projects/tuberculosis-classifier/Anndata_problem.py", line 16, in <module>
    next(iter(dataloader2))
  File "/home/icb/christophe.vetter/anaconda3/envs/tuberculosis_p3.8/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/icb/christophe.vetter/anaconda3/envs/tuberculosis_p3.8/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/icb/christophe.vetter/anaconda3/envs/tuberculosis_p3.8/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/icb/christophe.vetter/anaconda3/envs/tuberculosis_p3.8/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/icb/christophe.vetter/anaconda3/envs/tuberculosis_p3.8/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/icb/christophe.vetter/anaconda3/envs/tuberculosis_p3.8/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/icb/christophe.vetter/anaconda3/envs/tuberculosis_p3.8/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 180, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'anndata.experimental.multi_files._anncollection.AnnCollectionView'>
```

error n°2:
```
Traceback (most recent call last):
  File "/storage/groups/ml01/workspace/christophe.vetter/projects/tuberculosis-classifier/Anndata_problem.py", line 19, in <module>
    next(iter(dataloader3))
  File "/home/icb/christophe.vetter/anaconda3/envs/tuberculosis_p3.8/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/icb/christophe.vetter/anaconda3/envs/tuberculosis_p3.8/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/icb/christophe.vetter/anaconda3/envs/tuberculosis_p3.8/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/icb/christophe.vetter/anaconda3/envs/tuberculosis_p3.8/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 180, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'anndata.experimental.multi_files._anncollection.AnnCollectionView'>
```

My anndata version is 0.8.0.

**Comment by Koncopd** [comment]
As for num_workers, yes, it is not implemented and also makes no sense to use parallel gathering of indices and then collating for an `AnnData` or `AnnCollection` object. As for `batch_size`, i will check.

**Comment by ChrisHTV** [comment]
Ok, thank you. I hope you don't think the batch_size problem is too petty, as batch_size = 1 is not realistic. It is actually more about batch_size = 1 being the default, so that the Ann_Loader throws an exception when you don't specify batch_size.

**Comment by Koncopd** [comment]
Yes, thanks, you are right.

**Comment by Zethson** [comment]
This issue has been stale for years. Could you please try https://annbatch.readthedocs.io/en/stable/ and see whether it suits your needs. If not, please let us know. In the meantime, I'll close this. Thanks!
