### ISSUE TITLE
Better customization of chunking

### ISSUE THREAD

**Issue by multimeric** [scverse/anndata#961]
Chunking is quite quite an important factor in optimising speed, memory usage and disk usage of the H5AD file. However, `anndata` doesn't easily provide configuration of the chunking. Ideally the following could be improved:

* `AnnData.write` should have a `chunks` argument which in some way is passed to `h5py.create_dataset()`
* Both the above function, and the existing `anndata._io._write_h5ad` should support chunking on a *per-dataset* basis. In other words, I would like to see `AnnData.write(chunks = {"X": {"chunks": True}})`. The reason this is needed is because currently `dataset_kwargs` are passed to all datasets, even scalar ones, which can cause chunking to fail:
```python
>>> anndata._io._write_h5ad("AnnDataBench2/1e334b97669e392c2b71615fe975f999.h5ad", ad, dataset_kwargs = dict(chunks = True))
Traceback (most recent call last):
  File "/home/users/allstaff/milton.m/.conda/envs/miltonm-base/lib/python3.10/site-packages/anndata/_io/utils.py", line 214, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/home/users/allstaff/milton.m/.conda/envs/miltonm-base/lib/python3.10/site-packages/anndata/_io/specs/registry.py", line 175, in write_elem
    _REGISTRY.get_writer(dest_type, t, modifiers)(f, k, elem, *args, **kwargs)
  File "/home/users/allstaff/milton.m/.conda/envs/miltonm-base/lib/python3.10/site-packages/anndata/_io/specs/registry.py", line 24, in wrapper
    result = func(g, k, *args, **kwargs)
  File "/home/users/allstaff/milton.m/.conda/envs/miltonm-base/lib/python3.10/site-packages/anndata/_io/specs/methods.py", line 745, in write_string
    f.create_dataset(
  File "/home/users/allstaff/milton.m/.conda/envs/miltonm-base/lib/python3.10/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/home/users/allstaff/milton.m/.conda/envs/miltonm-base/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 106, in make_new_dset
    dcpl = filters.fill_dcpl(
  File "/home/users/allstaff/milton.m/.conda/envs/miltonm-base/lib/python3.10/site-packages/h5py/_hl/filters.py", line 158, in fill_dcpl
    raise TypeError(
TypeError: Scalar datasets don't support chunk/filter options

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/allstaff/milton.m/.conda/envs/miltonm-base/lib/python3.10/site-packages/anndata/_io/h5ad.py", line 105, in write_h5ad
    write_elem(f, "uns", dict(adata.uns), dataset_kwargs=dataset_kwargs)
  File "/home/users/allstaff/milton.m/.conda/envs/miltonm-base/lib/python3.10/site-packages/anndata/_io/utils.py", line 214, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/home/users/allstaff/milton.m/.conda/envs/miltonm-base/lib/python3.10/site-packages/anndata/_io/specs/registry.py", line 175, in write_elem
    _REGISTRY.get_writer(dest_type, t, modifiers)(f, k, elem, *args, **kwargs)
  File "/home/users/allstaff/milton.m/.conda/envs/miltonm-base/lib/python3.10/site-packages/anndata/_io/specs/registry.py", line 24, in wrapper
    result = func(g, k, *args, **kwargs)
  File "/home/users/allstaff/milton.m/.conda/envs/miltonm-base/lib/python3.10/site-packages/anndata/_io/specs/methods.py", line 281, in write_mapping
    write_elem(g, sub_k, sub_v, dataset_kwargs=dataset_kwargs)
  File "/home/users/allstaff/milton.m/.conda/envs/miltonm-base/lib/python3.10/site-packages/anndata/_io/utils.py", line 220, in func_wrapper
    raise type(e)(
TypeError: Scalar datasets don't support chunk/filter options

Above error raised while writing key 'X_name' of <class 'h5py._hl.group.Group'> to /
>>> ad.X.shape
(17844, 60661)
```

**Comment by ivirshup** [comment]
Hey @multimeric, sorry about the late response here.

I broadly agree with this. But would note it's currently a little difficult to have a single chunk argument that can be used across all the different types. I do think the specific case you ran into does look like a bug.

This use case is part of why we implemented the new `write_dispatched` method. For something you can do right now, I would recommend taking a look at this example from our tests:

https://github.com/scverse/anndata/blob/dcee1e5c5788482a5a1aa3065c081bf703d4ad08/anndata/tests/test_io_dispatched.py#L90-L124
